# changes to this workflow should also be made in subtrees

name: Release
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 5,* * * *'

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
      - run: npm ci
      - run: npm run -s relnotes | tee relnotes.txt
      - uses: softprops/action-gh-release@v1
        with: { body_path: relnotes.txt }

  major-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          tag: ${{github.ref}}
        run: |
          tag=${tag#refs/tags/}
          major=${tag%%.*}
          git push -f origin HEAD:refs/heads/$major
